# Site settings
title: Yuta Akiya

# Author
author:
  name: Yuta Akiya
  desc: Aspiring Data Analyst
  email: 
  selfie: assets/img/profile.jpg

# social
social:
  email: false
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: yutaa51
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/yuta-akiya-00596a203/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
